### ISSUE TITLE
[BUG] - Plus de mise à jour des data

### ISSUE THREAD

**Issue by DamsPer** [MyElectricalData/myelectricaldata#315]
**Description du bug**
Depuis 2 jours, les datas ne sont pas mise à jour et j'ai cette erreur dans HomeAssistant : 
```
WARNING : Execution of job "fetch_data (trigger: interval[1:00:00], next run at: 2023-03-28 08:21:20 CEST)" skipped: maximum number of running instances reached (1) 
```

Je fais un A/R du module est ça retombe en marche. 

**Configuration**
```
myelectricaldata:
  PDL:
    enable: 'true'
    addresses: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.1841'
    consumption_price_hc: '0.1470'
    consumption_price_hp: '0.1841'
    #offpeak_hours: null
    offpeak_hours_0: 23H36-7H36               # LUNDI
    offpeak_hours_1: 23H36-7H36               # MARDI
    offpeak_hours_2: 23H36-7H36               # MERCREDI
    offpeak_hours_3: 23H36-7H36               # JEUDI
    offpeak_hours_4: 23H36-7H36               # VENDREDI
    offpeak_hours_5: 23H36-7H36               # SAMEDI
    offpeak_hours_6: 23H36-7H36               # DIMANCHE
    plan: HP/HC
    production: 'false'
    production_detail: 'false'
    refresh_addresses: 'false'
    refresh_contract: 'false'
```

**Type d'installation**
Home Assistant 2023.3.6
Supervisor 2023.03.2
Interface utilisateur : 20230309.1 - latest

**Version : 0.8.13-11**
