### ISSUE TITLE
[FEATURES] - Ne pas réécrire tout influxdb à chaque update

### ISSUE THREAD

**Issue by ahurtaud** [MyElectricalData/myelectricaldata#317]
Bonjour,

je voudrais une synchronisation influxdb quotidiennement mise à jour avec les nouveaux relevés.
Aujourd'hui ca fonctionne bien avec ma config, mais il réécrit quotidiennement les memes points de 2020 jusquà 2023...
Ca utilise beaucoup de resources sur mon influx pour rien, j'ai deja ces points.

Feature request.
Ne réécrire vers influxdb que les nouveaux relevés, ou bien utiliser la config `consumption_max_date` et `consumption_detail_max_date` pour ne réécrire que les points après ces dates (ce qui ne semble pas etre le cas aujourd'hui, cf ma config en dessous).

<details>
  <summary>config.yaml</summary>
  
  ```yaml
cycle: 14400 # 4H
debug: true
wipe_influxdb: false
home_assistant:
    enable: false
influxdb:
    enable: true
    hostname: 192.168.1.100
    port: 8086
    token: XXX
    org: myelectricaldata
    bucket: myelectricaldata
    # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
    # mais va augmenter la consommation mémoire & CPU et donca activer uniquement sur un hardware robuste.
    method: synchronous # Mode disponible : synchronous / asynchronous / batching
mqtt:
    enable: false
myelectricaldata:
    "XXX":
      enable: "true"
      token: XXX
      name: "Maison"
      addresses: "true"
      cache: "true"
      consumption: "true"
      consumption_detail: "true"
      consumption_price_base: "0.2062"
      consumption_price_hc: "0.2062"
      consumption_price_hp: "0.2062"
      consumption_max_date: "2023-02-26"
      consumption_detail_max_date: "2023-02-26"
      offpeak_hours_0: "" # LUNDI
      offpeak_hours_1: "" # MARDI
      offpeak_hours_2: "" # MERCREDI
      offpeak_hours_3: "" # JEUDI
      offpeak_hours_4: "" # VENDREDI
      offpeak_hours_5: "" # SAMEDI
      offpeak_hours_6: "" # DIMANCHE
      plan: "BASE"
      production: "false"
      production_detail: "false"
      refresh_addresse: "false"
      refresh_contract: "true"

  ```
  
</details>
