### ISSUE TITLE
[HELP] - Décalage des horaires : Comment bien configurer la timezone ?

### ISSUE THREAD

**Issue by nanawel** [MyElectricalData/myelectricaldata#321]
**Description de la fonctionnalité**
Malgré une configuration qui semble correcte, j'obtiens toujours _dans Grafana et dans Influxd_ des mesures dont les horaires sont décalés, comme si la notion de timezone était ignorée.

En hiver c'était 1h de décalage, en été c'est à présent 2h de décalage.

Quand j'observe les mesures dans l'interface web, les horaires sont **corrects** (ici ma référence est une puissance de 1338 W vers 19h le 09/04) :
![image](https://user-images.githubusercontent.com/4866761/231446737-dd957dda-4b9e-4e89-a70c-d3a4095dd69a.png)

Confirmation par la métrologie d'Enedis : 
![image](https://user-images.githubusercontent.com/4866761/231449799-0ae95298-bdd8-4f0a-bf8f-f01d177b56d6.png)

Cependant, quand je regarde dans Influxd, je vois que l'horaire enregistré est la valeur FR, mais avec la timezone UTC, ce qui est par conséquent **invalide**.
![image](https://user-images.githubusercontent.com/4866761/231449384-b657578f-d011-40a6-9fb8-7cc89ca5c832.png)

Une fois dans Grafana, c'est le même problème, ce qui est logique puisque l'heure enregistrée pour la mesure est 19:00 UTC soit 21:00 FR (Europe/Paris).

J'utilise une stack Docker avec la configuration suivante (je n'ai laissé que les sections intéressantes) : 

```yaml
version: "3.9"

services:
  app:
    image: m4dm4rtig4n/myelectricaldata:0.8.14
    volumes:
      - ./volumes/app-data:/data
    environment:
      TZ: Europe/Paris
    depends_on:
      - db

  db:
    image: influxdb:2.6
    volumes:
      - ./volumes/db-data:/var/lib/influxdb2
      - ./volumes/db-config:/etc/influxdb2
    environment:
      TZ: Europe/Paris
```

J'ai également essayé avec/sans la variable `TZ` sur le container influxdb mais cela ne change rien (en supprimant les fichiers de base entre chaque essai, évidemment).

**Type d'installation**
Docker

**Version**
0.8.14

```
Digest: sha256:86cde9894d4ade19ad5aa132322fcb92d7d5e187f1d3c06f704c8c062d8f8a2e
Status: Downloaded newer image for m4dm4rtig4n/myelectricaldata:0.8.14
docker.io/m4dm4rtig4n/myelectricaldata:0.8.14
```

**Comment by dudu7731** [comment]
Bonjour dans influxdb on peut ajuster la TZ : 
import "timezone"
option location = timezone.location(name: "Europe/Paris")

**Comment by nanawel** [comment]
@dudu7731 Je dépends du connecteur Influxdb de myelectricaldata sur cet aspect. C'est lui qui est sensé gérer correctement la timezone lors de l'export de données vers la base.

**Comment by m4dm4rtig4n** [comment]
Dans mes souvenirs, je ne défini pas de TZ dans ce que j'envoie dans l'influxdb car ca génére plus d'emmerde qu'autre chose... :/
Il y a moulte post à ce sujet sur le forum d'influxdb.

C'est un sujet que j'avais déjà eu avec plusieurs autre utilisateurs et la conclusion était de ne pas définir la TZ comme l'outils fonctionne en mono zone dans tt les cas.

**Comment by pbranly** [comment]
On retrouve ce vieux problème de la mesure daily d'enedis a 00h30 local time .
Cette mesure est retraduite par influx en UTC donc -1h en hivers et -2h en heure d'été .
@m4dm4rtig4n il y a eu tellement d'écrits à ce sujet il y a x années, que je ne sais plus mais je çrois que tu as justement essayé de mettre des TZ un peu partout sans succès .
La méthode bourrin consistait à décaler la mesure daily de x >2 heures afin d'échapper au problème. Mais tu n'as pas souhaité avec raison l'utiliser.
Sous grafana et avec l'aide de "certain" j'ai un Time Zone systématique dans mes configurations en Europe/Paris.
Cela permet d'avoir une égalité parfaite entre la somme des détails du jour avec le daily du même jour 
Je n'ai plus creusé après 
Phil

**Comment by nanawel** [comment]
Oui je comprends le problème : Enedis ne fournit pas de timezone dans les relevés puisqu'il est évident pour eux qu'il s'agit d'une heure FR (timezone `Europe/Paris`).

Sauf qu'il faudrait quand même préciser cette timezone lors du stockage de ces dates, car qu'on le veuille ou non, le format date impose de préciser cette donnée.

En cherchant un peu, je pense qu'un des problèmes vient par exemple de ce bout de code là : 

https://github.com/m4dm4rtig4n/myelectricaldata/blob/ae087c04503f4e9c94c9811bd416414ba2c6bb22/app/models/export_influxdb.py#L9-L38

Il y a en effet un

```python
utc=pytz.UTC
```

puis un
```python
            app.INFLUXDB.write(
                measurement=measurement_direction,
                date=utc.localize(date),
```

sauf que le `utc.localize()` ne convertit rien du tout, il appose simplement la timezone fixée sur la date, sans chercher à savoir si cela peut altérer son interprétation.

On passe donc par exemple de "2023-04-09 19:00:00" (soit "2023-04-09 19:00:00 **+02:00**" en réalité) à "2023-04-09 19:00:00 **+00:00**", ce qui est très différent !

On peut facilement reproduire le problème avec ce snippet : 

```python
import datetime
import dateutil.parser
import pytz

if __name__ == "__main__":
    mydate = dateutil.parser.isoparse("2023-04-09 20:00:00")
    utc = pytz.UTC
    fr = pytz.timezone("Europe/Paris")
    
    print(mydate)
    utcDate = utc.localize(mydate)
    print(utcDate)
    frDate = fr.localize(mydate)
    print(frDate)
```

Ce qui donne, depuis un ordinateur avec pourtant une timezone système à `Europe/Paris` : 

```
2023-04-09 20:00:00
2023-04-09 20:00:00+00:00
2023-04-09 20:00:00+02:00
```

**Comment by m4dm4rtig4n** [comment]
@nanawel c'est pas une histoire de faisabilité, mais plus de facilité d'exploitation de données.
Dans les 1ere version j'avais set le TZ dans l'influxdb, et j'ai du rollback la modif car ca généré plus de merde qu'autre chose :/

Et si tu va voir sur le forum d'influxdb, la majorité des utilisateurs d'influxdb ne set pas de TZ en mono-zone.

Une fois que tu set la TZ, si tu ne la renseigne pas correctement de bout en bout, tu te retrouve avec des décalage de fuseau et généré plus d"issue qu'autre chose.

Le plus simple est de set la TZ lors de l'exploitation des data car tu sais que dans 100% des cas la donnée back est en UTC.

**Comment by nanawel** [comment]
> De plus Enedis envoie également en UTC.

Ah c'était une information que je n'avais pas, intéressant !

Je vais creuser un peu, ça me chagrine cette histoire. Ignorer la TZ quand on manipule des dates, c'est une histoire à se faire pincer les doigts à moyen ou long terme (je sais d'expérience :roll_eyes:).

**Comment by pbranly** [comment]
@m4dm4rtig4n  

"De plus Enedis envoie également en UTC."

Pour moi non. Enedis envoie en heure locale donc en CET.
Si c'était le cas, il n'y aurait pas de différence entre l'été et l'hiver.
Phil

**Comment by nanawel** [comment]
C'est bien ce qu'il me semblait, et qui semblait expliquer le noeud du problème ici.
Merci @pbranly pour ton retour.

**Comment by nanawel** [comment]
Désolé @m4dm4rtig4n pour les allers-retours incessants sur le sujet, mais merci pour ta participation active :hugs: 

Quand on fait un `curl` sur ton API proxy comme indiqué sur [la doc](https://www.myelectricaldata.fr/documentation), les horaires retournés sont en TZ Europe/Paris apparemment (il n'y a pas d'information de TZ dans la date elle-même, mais c'est ce que j'en conclus en comparant avec la métrologie Enedis).

Cela signifie que tu convertis ces valeurs côté serveur avant de les renvoyer en réponse, c'est bien ça ?
J'essaye de savoir si l'adaptation est encore possible côté appli cliente et si oui, comment elle pourrait être faite sans provoquer d'effet de bord.

**Comment by m4dm4rtig4n** [comment]
Le soucis est que si je change maintenant la TZ sur le projet, je vais décaler tts les données des autres utilisateurs qui ont prit l'habitude de bosser en UTC.
Ce n'est pas un changement anodin.

Et comme dit plus haut, bosser sur un autre TZ que l'UTC génére plus de soucis que d'avantage pour la majorité des utulisateurs.

Perso je choisi l'option la plus simple à mettre en oeuvre et qui génére le moins d'issue possible.

Après, j'ai une proposition qui est de rendre paramétrable le TZ via le fichier de config du style :
```
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  timezone: UTC # ou CET
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous    # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
```

**Comment by nanawel** [comment]
> Le soucis est que si je change maintenant la TZ sur le projet, je vais décaler tts les données des autres utilisateurs qui ont prit l'habitude de bosser en UTC.
> Ce n'est pas un changement anodin.

Complètement ! C'est pour ça que je voulais en savoir le plus possible pour réfléchir à une manière de rendre ça backward-compatible, au moyen d'une option facultative qui permettrait de conserver le fonctionnement actuel par défaut.

Une remarque peut-être : tu dis "les données des autres utilisateurs qui ont prit l'habitude de bosser en UTC", mais à mon sens personne ne travaille en UTC, de par le fait que les dates utilisées ne sont pas en UTC. À la rigueur on pourrait dire "les données des autres utilisateurs qui ont prit l'habitude de bosser sans TZ" (et qui _par défaut_ se retrouvent à avoir des dates estampillées "UTC" alors qu'elles ne le sont pas).

Je plussoie néanmoins ta proposition d'ajouter une clé de config pour gérer la timezone dans le fichier, ça me semble être une manière très élégante pour satisfaire tout le monde ! :+1:

**Comment by m4dm4rtig4n** [comment]
Si tu veut faire un test avec la  0.8.16-beta1 qui va pop dans quelques minutes, j'ai ajouter le gestion tu TZ dans l'import influxdb :

Exemple :
```
influxdb:
  bucket: myelectricaldata
  enable: true
  hostname: influxdb
  method: ASYNCHRONOUS
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
  timezone: "Europe/Paris"
```
Sachant que le default est :
```
  timezone: "Europe/Paris"
```
