### ISSUE TITLE
[BUG] - myelecticaldata.fr injoignable et données tempo non récupérables

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata#369]
**Description du bug**
J'ai des erreurs au démarrage, 
`

> 2023-05-04 08:32:33.892 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 2023-05-04 08:32:33.892 -     INFO :  RÉCUPÉRATION DES DONNÉES TEMPO :
> 2023-05-04 08:32:33.892 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> Traceback (most recent call last):
>   File "/app/models/jobs.py", line 60, in job_import_data
>     self.get_tempo()
>   File "/app/models/jobs.py", line 356, in get_tempo
>     return Tempo().get()
>   File "/app/models/query_tempo.py", line 57, in get
>     result = self.run()
>   File "/app/models/query_tempo.py", line 44, in run
>     "description": json.loads(query_response.text)["detail"]
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2023-05-04 08:32:34.161 -    ERROR : ═══════════════════════════════════════════════•°• :ERREUR: •°•════════════════════════════════════════════════
> 2023-05-04 08:32:34.161 -    ERROR :
> 2023-05-04 08:32:34.162 -    ERROR :  Erreur lors de la récupération des données tempo
> 2023-05-04 08:32:34.163 -    ERROR :  Expecting value: line 1 column 1 (char 0)
> 2023-05-04 08:32:34.163 -    ERROR :
> 2023-05-04 08:32:34.163 -    ERROR : ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════

`
et toutes les requêtes vers myelectricaldata.fr échouent ...

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: false
wipe_influxdb: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  bucket: MyElectricalData
  enable: true
  hostname: XXXXX
  method: asynchronous
  org: production
  port: 8086
  token: XXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: XXXXX
  password: XXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: admin
myelectricaldata:
  'XXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: 'true'
    consumption_price_base: '0.2062'
    consumption_price_hc: '0.114'
    consumption_price_hp: '0.1508'
    enable: 'true'
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
    token: XXX
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508

```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.8.16**
