### ISSUE TITLE
[FEATURES] - Support HTTPS pour dashboard sur port 5000

### ISSUE THREAD

**Issue by HermesHonshappo** [MyElectricalData/myelectricaldata#375]
Hello

Avant, j'avais tout installé sur HA, sur un boitier dédié.
Mais suite à des soucis de stabilité, je suis en train de tout basculer dans des docker séparés, que je gère indépendamment

J'ai donc fait une réinstall de MyElectricalData dans un docker, testé, et ça fonctionne.

Le seul inconvénient, c'est que les infos sont exposées sur le port 5000 en HTTP
Est-ce qu'il serait possible d'ajouter deux options dans le fichier de config pour spécifier les fichiers de certificats?  Et si ces options sont présentes, présenter l'interface en HTTPS et pas en HTTP?

Je demande ça, car pour intégrer l'interface de MED dans une page sur HA, par exemple, il est obligatoire que ce soit en HTTPS

Exemple de conf dans Zigbee2MQTT. La présence des deux lignes commençant par ssl_ dans la conf basculent l'interface en HTTPS

```
frontend:
  port: 8080
  url: https://Z2M-server.example.com
  ssl_cert: /app/data/fullchain.pem
  ssl_key: /app/data/privkey.pem
```
