### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by Xen3r0** [MyElectricalData/myelectricaldata#400]
**Description du bug**
Lors du démarrage du module sur Home Assistant, j'ai l'erreur suivante :

```
2023-08-23 15:59:26.477 -     INFO : Consommation :
Traceback (most recent call last):
  File "/app/models/jobs.py", line 391, in stat_price
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 379, in run
    Stat(usage_point_id=usage_point_id, measurement_direction="consumption").generate_price()
  File "/app/models/stat.py", line 636, in generate_price
    tempo_data = self.db.get_tempo_range(data[0].date, data[-1].date)
                                         ~~~~^^^
IndexError: list index out of range
```

Est-ce que c'est à cause de ma configuration ? Un bug dans le code ?

Merci pour votre aide

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
port: 5000
debug: false
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
# storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
influxdb:
  enable: true
  hostname: a0d7b954-influxdb
  port: 8086
  token: myelectricaldata:myelectricaldata
  org: "-"
  bucket: "myelectricaldata/autogen"
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: 192.168.1.70
  port: 1883
  username: mqtt
  password: mqtt
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "XXXXX":
    enable: true
    token: "XXXX"
    name: "Résidence principale"
    cache: true
    consumption: true
    consumption_detail: true
    consumption_price_base: "0.2142"
    consumption_price_hc: "0.2142"
    consumption_price_hp: "0.2142"
    consumption_max_date: "2024-08-23"
    consumption_detail_max_date: "2024-08-23"
    offpeak_hours_0: 3H40-8h10;12H40-16H10
    offpeak_hours_1: 3H40-8h10;12H40-16H10
    offpeak_hours_2: 0H00-23h59
    offpeak_hours_3: 3H40-8h10;12H40-16H10
    offpeak_hours_4: 3H40-8h10;12H40-16H10
    offpeak_hours_5: 0H00-23h59
    offpeak_hours_6: 0H00-23h59
    production: false
    production_detail: false
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.9.1**
